Add ruamel.yaml==0.18.14 to CLI deps (#3297)
Currently, it's not listed in package dependencies and when users
execute simple `apolo` without command and arguments, they get error
instead of help page:

```
$ apolo
ERROR: No module named 'ruamel'
Traceback (most recent call last):
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 562, in main
    cli.main(
    ~~~~~~~~^
        args=args,
        ^^^^^^^^^^
        standalone_mode=False,
        ^^^^^^^^^^^^^^^^^^^^^^
        windows_expand_args=False,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/utils.py", line 330, in invoke
    print_help(ctx)
    ~~~~~~~~~~^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/utils.py", line 350, in print_help
    pager_maybe(ctx.get_help().splitlines(), tty, terminal_size)
                ~~~~~~~~~~~~^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/click/core.py", line 730, in get_help
    return self.command.get_help(self)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/click/core.py", line 1064, in get_help
    self.format_help(ctx, formatter)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/click/core.py", line 1104, in format_help
    self.format_options(ctx, formatter)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 253, in
format_options
    self.format_commands(ctx, formatter)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 231, in
format_commands
    for subcommand in self.list_commands(ctx):
                      ~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 272, in
list_commands
    self._pre_load()
    ~~~~~~~~~~~~~~^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 278, in _pre_load
    self._pre_load(name)
    ~~~~~~~~~~~~~~^^^^^^
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/main.py", line 285, in _pre_load
    module = import_module(mod)
  File
"/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py",
line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/app_template.py", line 13, in
<module>
    from .template_schema_utils import _generate_yaml_from_schema
  File "/Users/ysem/.local/pipx/venvs/apolo-all/lib/python3.13/site-packages/apolo_cli/template_schema_utils.py", line 4,
in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
Full logs are available under /Users/ysem/.apolo/logs/apolo-run-2025-07-11_13-00-05.txt
```