Fix ci github release stage (#3223)
This issue created because of the failed deploy stage:
https://github.com/neuro-inc/apolo-cli/actions/runs/14244899467/job/39923877706

```
Run aio-libs/get-releasenote@v1.4.5
/usr/bin/docker run --name f3c52ec4cdba071edf4a1cb0f268a91da9c3bc_8be0d6 --label f3c52e --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_CHANGES_FILE" -e "INPUT_OUTPUT_FILE" -e "INPUT_VERSION" -e "INPUT_VERSION_FILE" -e "INPUT_START_LINE" -e "INPUT_HEAD_LINE" -e "INPUT_FIX_ISSUE_REGEX" -e "INPUT_FIX_ISSUE_REPL" -e "INPUT_NAME" -e "INPUT_DIST_DIR" -e "INPUT_CHECK_REF" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION_PATH" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/apolo-cli/apolo-cli":"/github/workspace" f3c52e:c4cdba071edf4a1cb0f268a91da9c3bc
Traceback (most recent call last):
  File "/get_releasenote.py", line 255, in <module>
    sys.exit(main())
  File "/get_releasenote.py", line 226, in main
    info = analyze_dists(root, os.environ["INPUT_DIST_DIR"])
  File "/get_releasenote.py", line 58, in analyze_dists
    assert name == nam, f"{nam} != {name} for {dist}"
AssertionError: apolo-cli != apolo-sdk for /github/workspace/dist/apolo_cli-25.4.1-py3-none-any.whl
```

The issue is that we have 2 wheels in the dist and in
`aio-libs/create-release` in the script
https://github.com/aio-libs/get-releasenote/blob/a3644a753299b7438eff2b3648123e8a12371589/get_releasenote.py#L46
`dists.iterdir()` returns in nondeterministic order files so
`version_file` can be invalid.

I propose as the simplest solution is to remove `cp apolo-sdk/dist/*
dist/` from the dist

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>